### ISSUE TITLE
Ignore trailing slash

### ISSUE THREAD

**Issue by bartek1912** [aheissenberger/serverless-offline-sqs#1]
Hello,
AWS sdk for go works strangely and it sends request ending with /, e.g. `http://localhost:9324/queue/MyQueue/`. Those requests are rejected by plugin: 
```
An error occurred (Invalid request: MissingQueryParamRejection(QueueName), MissingFormFieldRejection(QueueUrl)) when calling the SendMessage operation: Invalid request: MissingQueryParamRejection(QueueName), MissingFormFieldRejection(QueueUrl); see the SQS docs.
```

It can be easily reproduced:
1. works: `aws sqs --region "X" --endpoint-url http://localhost:9324 send-message --queue-url http://localhost:9324/queue/MyQueue  --message-body "MyFirstMessage"`
1. doesn't work: `aws sqs --region "X" --endpoint-url http://localhost:9324 send-message --queue-url http://localhost:9324/queue/MyQueue/  --message-body "MyFirstMessage"`

**Comment by aheissenberger** [comment]
Hi,

this Plugin is only a wrapper and does not handle the request. 
You have to ask the guys who provide the fake local sqs:

https://github.com/s12v/elasticmq-docker
